default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  socket: <%= ENV['DB_SOCKET'] %>
  google_project_id: <%= ENV['GOOGLE_PROJECT_ID'] %>
  storage_bucket_name: <%= ENV['STORAGE_BUCKET_NAME'] %>
  rails_master_key: <%= ENV['RAILS_MASTER_KEY'] %>
  storage_bucket_name: <%= ENV['STORAGE_BUCKET_NAME'] %>
